version: '3.8'
services:

  kanban-postgres:
    image: "postgres:13-alpine"
    env_file:
      - .env
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kanban-data:/var/lib/postgresql/data

  kanban-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban-app
    env_file:
      - .env
    environment:
      DB_HOST: kanban-postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB_NAME}
      STRIPE_SECRETKEY: ${STRIPE_SECRET_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "8080:8080"
    depends_on:
          - kanban-postgres

  kanban-ui:
    build:
      context: ../music-store-frontend
      dockerfile: Dockerfile_Production
    container_name: kanban-ui
    ports:
      - "4200:80"
    depends_on:
      - kanban-app

volumes:
  kanban-data:
