version: '3.8'
services:

  kanban-postgres:
    image: "postgres:13-alpine"
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: music-store
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - kanban-data:/var/lib/postgresql/data

  kanban-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban-app
    environment:
      DB_HOST: kanban-postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_NAME: music-store
      STRIPE_SECRETKEY: 51ObJ8dGilE1or8vMq7WqZQOS0BEp1whxzkL8NDaYJJyVlbOnRV3Rm7lM77mqbV5gBy9iL7qpOeuqqDnaKDiGmhcN00ue0gp8az
    ports:
      - "8080:8080"
    depends_on:
          - kanban-postgres

  kanban-ui:
    build:
      context: ../music-store-frontend
      dockerfile: Dockerfile_Production
    container_name: kanban-ui
    ports:
      - "4200:80"
    depends_on:
      - kanban-app

volumes:
  kanban-data:
